version: '3.7'

services:
    web:
        container_name: api        
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - .:/usr/src/app      
        ports:
            - ${PORT}:${PORT}